### ISSUE TITLE
Massive Delay after Purchase

### ISSUE THREAD

**Issue by JohnS19** [enjin/Enjin-Minecraft-Plugin#14]
Players purchase from the store and the payment goes through fine but the commands are not executed.

![image](https://user-images.githubusercontent.com/48459351/63907050-d37ad800-c9ce-11e9-9e7d-7922abc05414.png)

The player has been online for 15 minutes and has also tried relogging and waiting another 5 minutes. Enjin just refuses to view the player. The username of the player is simple and correct.

When removing the player login requirement, it just says this:
![image](https://user-images.githubusercontent.com/48459351/63907250-93682500-c9cf-11e9-89bb-b371e2e89234.png)

**Comment by JohnS19** [comment]
Plugin EnjinMinecraftPlugin v3.5.10 generated an exception while executing task 181

**Comment by Favorlock** [comment]
This is likely related to #13.

I need the full stack trace and the enjin report to continue investigating.

**Comment by JohnS19** [comment]
I will send the enjin report in a little while.

The UUID was being detected by the plugin multiple times throughout the period and the commands were on standby but it never executed. **The commands finally executed once the server restarted.**

**Comment by JohnS19** [comment]
Oh yep, its related to #13

**Comment by Favorlock** [comment]
Did you try the attached build in my response on that thread? If so, did it resolve the issue?
