### ISSUE TITLE
Currently getting an error about syncing with Enjin services not working.

### ISSUE THREAD

**Issue by SkuadMC** [enjin/Enjin-Minecraft-Plugin#16]
`[11:48:39 ERROR]: [com.enjin.bukkit.EnjinMinecraftPlugin] An error occured while syncing with Enjin services...
java.lang.NullPointerException: null
[11:49:39 ERROR]: [com.enjin.bukkit.EnjinMinecraftPlugin] An error occured while syncing with Enjin services...
java.lang.NullPointerException: null`

This only started after the latest update released on Spigot.

**Comment by Favorlock** [comment]
This is related to #15.
