### ISSUE TITLE
Support for NukkitX

### ISSUE THREAD

**Issue by jrodr10** [enjin/Enjin-Minecraft-Plugin#19]
## Prerequisites

Please answer the following questions before submitting an issue.

- [x] I checked to make sure that this issue has not already been filed

## Feature Description

Please describe the feature you wish to have added.

Support for NukkitX Server Software for Minecraft Bedrock Edition Servers. 

https://github.com/NukkitX/Nukkit

**Comment by Favorlock** [comment]
Thanks for the suggestion. At this time we are unable to add support for other platforms, however, if someone in the community wishes to implement support for NukkitX we will gladly accept a pull request if it meets quality standards.
