### ISSUE TITLE
CommandBank error on startup

### ISSUE THREAD

**Issue by GITVenox** [enjin/Enjin-Minecraft-Plugin#20]
## Prerequisites

Please answer the following questions before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I didn't use ```/reload```

## Expected Behavior

I expected no errors.

## Current Behavior

The plugin still works as I thought it would, but maybe I just can't see what is broken.

## Failure Information

`16.11 09:04:02 [Server] ERROR [com.enjin.bukkit.EnjinMinecraftPlugin] Exception Caught:`

## Steps to Reproduce 

Please provide detailed steps for reproducing the issue if applicable.

1. Download the plugin
2. Run the server

## Context

Please provide any relevant information about your setup.
This is important in case the issue is not reproducible except under certain circumstances.

### Server Platform

- [x] Spigot
- [x] Paper
- [ ] Sponge
- [ ] Bungee
- [ ] Other:

Version:

### Java

Version:  git-Paper-135, MC 1.14.4

## Enjin Report

[enjinreport_2019-11-16_10.03.56.zip](https://github.com/enjin/Enjin-Minecraft-Plugin/files/3854327/enjinreport_2019-11-16_10.03.56.zip)

**Comment by Favorlock** [comment]
Are you using a custom command instead of buy in the EMP config? If so, a temporary solution is to use the standard buy command.

**Comment by GITVenox** [comment]
I'm using "enjinbuy" because I already have a "buy" and I don't use Enjin Webstore

**Comment by Favorlock** [comment]
You can download a fixed version from https://github.com/enjin/Enjin-Minecraft-Plugin/releases/tag/v3.5.14

I've tested this on Paper 1.14.4 and it's working now so I'm going to close this issue. If you still experience issues please let me know.
