### ISSUE TITLE
Remove the console spam

### ISSUE THREAD

**Issue by GITVenox** [enjin/Enjin-Minecraft-Plugin#21]
## Prerequisites

Please answer the following questions before submitting an issue.

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

## Feature Description

I want all the stuff in the console to be removed when it's syncing with Enjin Services.

**Comment by Favorlock** [comment]
Can you give an example?

**Comment by GITVenox** [comment]
`[INFO] [DEBUG] Syncing with Enjin services...
[INFO] [DEBUG] Constructing payload...
[INFO] [DEBUG] Fetching plugin service...
[INFO] [DEBUG] Syncing...
[INFO] [DEBUG] Enjin API URL: https://api.enjin.com/api/v1/minecraft.php
[INFO] [DEBUG] JSONRPC2 Request: {"method":"Plugin.sync","id":133,"params":{"authkey":"**************************************************","status":{"worlds":["hub","hub_nether","hub_the_end","hide","world_the_end","world","world_nether","map1","flat","creative"],"hasranks":true,"plugins":["CoreProtect","dynmap","LuckPerms","Wild","WorldEdit","PlaceholderAPI","PacketListenerApi","UltimateTimber","ProtocolLib","Multiverse-Core","Multitool","LuckPerms-GUI","OldCombatMechanics","SerialKey","Multiverse-Inventories","TrollBoss","Multiverse-Portals","Vault","StaffPlus","GriefPrevention","Spiderman","MineTinker-Elevators","VentureChat","Essentials","RankGrantPlus","KillerMoney","HolographicDisplays","BuycraftX","Shopkeepers","DiscordSRV","Dynmap-GriefPrevention","Shop","Multiverse-NetherPortals","SuperVanish","EssentialsSpawn","UltimateKits","EnjinMinecraftPlugin","Dynmap-Essentials","UltimateStacker","UltimateCatcher"],"players":0,"groups":["owner","mod","oscorp","legend","venox","admin","hero","default","known","builder","vip","scorp"],"playerlist":[],"playergroups":{},"mc_version":"1.14.4","stats":null,"tps":20.0,"votifier":null,"java_version":"1.8.0_222","executed_commands":[],"pluginversion":"3.5.7","maxplayers":10}},"jsonrpc":"2.0"}
[INFO] [DEBUG] JSONRPC2 Response: {"result":{"instructions":[],"status":"ok"},"id":"133","jsonrpc":"2.0"}
[INFO] [DEBUG] Sync complete...`

**Comment by Favorlock** [comment]
First things first you need to update your version. The latest is v3.5.13 which you can download from the Spigot resource page https://www.spigotmc.org/resources/enjin-cms-donationcraft-plugin.17209/
