### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Strummm** [enjin/Enjin-Minecraft-Plugin#23]
## Prerequisites

Please answer the following questions before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I didn't use ```/reload```

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

What is the current behavior

## Failure Information

To assist the developers in resolving the issue please provide any additional information.
Please use pastebin.com or file attachment for stack-traces and logs.

## Steps to Reproduce 

Please provide detailed steps for reproducing the issue if applicable.

Using a command on my server.
https://hasteb.in/yikogiza.md

## Context

Please provide any relevant information about your setup.
This is important in case the issue is not reproducible except under certain circumstances.

### Server Platform

- [x] Spigot
- [ ] Paper
- [ ] Sponge
- [ ] Bungee
- [ ] Other:

Version:

### Java

Version:

## Enjin Report
Enjin report not sending anything
Please generate an Enjin report with the command ```/enjin report``` and attach it to the issue.

**Comment by Favorlock** [comment]
The latest versions of EMP do not support the version of Minecraft you are using. As such this is not an issue we can address.
