### ISSUE TITLE
Error code 429

### ISSUE THREAD

**Issue by STG-Allen** [enjin/Enjin-Minecraft-Plugin#24]
I am currently working on porting enjin to velocity. However, I've run into an issue when loading the plugin. I have noticed that when I run the plugin on my server machine it fails to authenticate and gives me the following error
`Network exception: Server returned HTTP response code: 429 for URL: http://api.enjin.com/api/v1/minecraft.php`

Now while I assume this is normal behavior, is there any way I can get in contact with someone to help speed the testing along so that I wouldn't have to wait out the timeout period?

https://github.com/STG-Allen/Enjin-Minecraft-Plugin

**Comment by Favorlock** [comment]
Hi there, unfortunately we can't make any exceptions when it comes API calls.
