### ISSUE TITLE
Error when player joins

### ISSUE THREAD

**Issue by A-Valk** [enjin/Enjin-Minecraft-Plugin#5]
I get this error in my console every time a player joins
Running the latest paper build (paper-66)

https://pastebin.com/GgwWzkYS

**Comment by A-Valk** [comment]
on further inspection this happens every x minutes, not just when a player joins (player joins were just really well timed XD)

**Comment by Favorlock** [comment]
Have you updated to the latest version? That should've already been resolved.

https://www.spigotmc.org/resources/enjin-cms-donationcraft-plugin.17209/update?update=280219
