### ISSUE TITLE
Lag with Votifier

### ISSUE THREAD

**Issue by feelbetta** [enjin/Enjin-Minecraft-Plugin#6]
I have a similar issue to this user on his Issue ticker for NuVotifier:

https://github.com/NuVotifier/NuVotifier/issues/143

According to the developer, and the stacktrace, it's caused by the enjin plugin. Any way it can get addressed?

**Comment by Favorlock** [comment]
@feelbetta Could you try getting some spigot timings?

The line in question is https://github.com/enjin/Enjin-Minecraft-Plugin/blob/master/bukkit/src/main/java/com/enjin/bukkit/listeners/VotifierListener.java#L44 which doesn't strike me as a method that should be capable of crashing the server.

**Comment by Favorlock** [comment]
I've reverted the vote handling to be as similar to the way it was done in 2.x to see if that changes anything. You can grab the plugin jar from the following link:

https://drive.google.com/open?id=1ZnhsWM92nRl0bsTIlipCnT-fZGQXg7T8

Let me know if this works for you.

**Comment by Favorlock** [comment]
After further consultation with the NuVotifier dev things should be good now.

**Comment by Favorlock** [comment]
Assuming things are working with the development build since I haven't heard otherwise.

Closing the issue.
