### ISSUE TITLE
High Resource usage from Enjin

### ISSUE THREAD

**Issue by ElFlyGod** [enjin/Enjin-Minecraft-Plugin#9]
Happens on player login and disconnect.
http://prntscr.com/o94hc1

Full timings: https://timings.aikar.co/?id=698a872e875d4f989f8d90374c8e71a5

PS: When you send a fixed version please include the votifier lag patch you made in feelbettas ticket a while ago, it helped solve the lag from that.
https://github.com/enjin/Enjin-Minecraft-Plugin/issues/6

**Comment by Favorlock** [comment]
Have you tried the version found at https://github.com/enjin/Enjin-Minecraft-Plugin/releases/tag/v3.5.7?

I upload builds to the github release page before they are published to spigot forums as I don't control the account for that.

**Comment by ElFlyGod** [comment]
What i meant is, there is a performance issue when players login and log out, this isnt related to voting i just said if you could include the voting fix from earlier that would be good

**Comment by ElFlyGod** [comment]
Still need help, this is not solved...

**Comment by ElFlyGod** [comment]
still having issues, need help.

**Comment by Favorlock** [comment]
I have uploaded a new build at https://github.com/enjin/Enjin-Minecraft-Plugin/releases/tag/v3.5.10. I have refactored some of the references you mentioned to perform functions async where appropriate and config saving now runs on a 1 minute timer. Let me know how things work out for you. If I don't hear back within the week I'll assume things are working and will close the issue.
